# Generated by Django 2.2.24 on 2021-06-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_birth', models.DateField()),
                ('email', models.CharField(max_length=50)),
                ('course', models.ManyToManyField(related_name='students', to='courses.Course')),
            ],
        ),
    ]
